name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip libgl1-mesa-dev
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip sdk.zip -d latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;25.2.9519653"

      - name: Build APK
        env:
          ANDROIDSDK: $HOME/android-sdk
          ANDROIDNDK: $HOME/android-sdk/ndk/25.2.9519653
          ANDROID_HOME: $HOME/android-sdk
          PATH: $HOME/.local/bin:$PATH
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: SemkaLoveMaho
          path: bin/*.apk
