name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies (Buildozer prerequisites)
      run: |
        sudo apt-get update -q
        sudo apt-get install -y --no-install-recommends \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          build-essential \
          python3-dev \
          libffi-dev \
          libssl-dev \
          libxml2-dev \
          libxslt1-dev \
          zlib1g-dev \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good
        curl -sS https://bootstrap.pypa.io/get-pip.py | python3
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Cython and Buildozer
      run: |
        python3 -m pip install --upgrade --user pip setuptools wheel cython
        python3 -m pip install --upgrade --user buildozer

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Android SDK licenses
      run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Update SDK components (optional but recommended)
      run: |
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-30" "build-tools;30.0.3"

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Cache Pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: bin/*.apk
        if-no-files-found: error
