name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git build-essential \
                              libncurses5 libstdc++6 libffi-dev libssl-dev \
                              libsqlite3-dev libjpeg-dev zlib1g-dev \
                              libandroid-tools adb

      - name: Install buildozer
        run: pip install buildozer

      - name: Build the APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: semkalovemaho-apk
          path: bin/*.apk
