name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev build-essential
          sudo apt install -y git
          sudo apt install -y openjdk-8-jdk
          sudo apt install -y unzip
          sudo apt install -y libncurses5 libstdc++6 lib32z1 libbz2-1.0
          pip install --upgrade pip
          pip install buildozer

      - name: Install Android SDK and NDK
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "build-tools;29.0.2" "platform-tools" "platforms;android-29"
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "ndk;21.3.6528147"
      
      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug
