name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          openjdk-17-jdk \
          unzip \
          wget \
          curl \
          git

    - name: Install Android dependencies
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        cd $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        rm android-ndk-r25b-linux.zip
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip
        rm sdk-tools-linux-4333796.zip
        ./tools/bin/sdkmanager --licenses
        ./tools/bin/sdkmanager --update
        ./tools/bin/sdkmanager "platforms;android-30"
        ./tools/bin/sdkmanager "build-tools;30.0.3"
        ./tools/bin/sdkmanager "ndk;25.2.5"

    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer

    - name: Build APK
      run: |
        cd $GITHUB_WORKSPACE
        buildozer android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-apk
        path: $GITHUB_WORKSPACE/bin/*.apk
